from __future__ import annotations

import pandas as pd
import matplotlib.pyplot as plt

from dms_datastore import read_ts
from vtools import cosine_lanczos
from vtools.functions.neighbor_fill import fill_from_neighbor, load_dfm_params

from . import paths

# Approximate time when NOAA transition complete. Contains overlap period.
NOAA_START = pd.Timestamp("2014-05-10")

# Frozen, hand-cleaned DWR/EMP Martinez record (1991-2017) that was the basis of
# the harmonic fit. Read directly here (via read_ts, which handles its metadata
# header); it is a legacy-only input and is not regenerated by prepare.
CLEANED_CSV = str(paths.CLEANED_LEGACY)


def _read_cleaned(fn: str) -> pd.Series:
    s = read_ts(fn)["value"].copy()
    s.index.name = "datetime"
    return s


def _read_value(fn: str) -> pd.Series:
    df = pd.read_csv(fn, index_col=0, parse_dates=True)
    if list(df.columns) != ["value"]:
        raise ValueError(f"{fn}: expected single column 'value', got {list(df.columns)}")
    s = df["value"].copy()
    s.index.name = "datetime"
    freqstr = pd.infer_freq(s.index)
    s = s.asfreq(freqstr)
    return s


def fill_mrz_legacy(
    *,
    dfm_yaml: str = str(paths.DFM_PARAMS),
    start: pd.Timestamp | None = None,
    end: pd.Timestamp | None = None,
    show: bool = True,
) -> None:
    """
    Construct a legacy (pre-NOAA) filled Martinez stage time series.

    This routine reproduces the historical Martinez stage filling method for
    filling prior to the availability of the NOAA Martinez station (beginning
    in mid-2013). It is intended for continuity with earlier analyses and
    harmonic studies, not as a replacement for the post-NOAA QA/QC-driven
    correction pipeline.

    The algorithm proceeds in two bands:

    **Subtidal band**
      1. Estimate Martinez subtidal stage using a 40-hour cosine-Lanczos filter
         applied to the hand-cleaned DWR/EMP Martinez record.
      2. Fill gaps in the Martinez subtidal using the Mallard subtidal
         (substitution).
      3. Smooth the filled subtidal using a dynamic factor model
         (DFM) with San Francisco subtidal as the neighbor, using pre-fitted
         parameters in dfm_yaml.

    **Tidal / residual band**
      4. Form a tidal residual by subtracting the filled subtidal from the
         cleaned Martinez record.
      5. Form a harmonic residual proxy by subtracting the harmonic
         subtidal (40-hour filtered) from the harmonic reconstruction.
      6. Fill Martinez tidal residual gaps by interpolating from the harmonic
         residual proxy.

    The final filled series is the sum of the filled subtidal and filled
    residual components.

    Parameters
    ----------
    do_dfm : bool, optional
        If True (default), apply DFM smoothing to the filled subtidal using
        San Francisco as a neighbor and parameters loaded from ``dfm_yaml``.
        If False, the subtidal is filled by Mallard substitution only.
    dfm_yaml : str, optional
        Path to the YAML file containing pre-fitted DFM parameters for
        subtidal smoothing. Only used if ``do_dfm=True``.
    start : pandas.Timestamp or None, optional
        Start time for the legacy fill. If None, the earliest available time
        in the cleaned Martinez record is used.
    end : pandas.Timestamp or None, optional
        End time for the legacy fill. If None, the series is truncated at the
        NOAA Martinez start date (2013-01-01).

    Outputs
    -------
    Writes a CSV file:
        ``mrz_stage_filled_legacy.csv``

    The output file:
      - has a regular 15-minute time base,
      - contains a single column named ``value``,
      - represents stage in the same implicit units as the input data.

    Notes
    -----
    * This function performs **no QA/QC flagging** and does not attempt to
      diagnose clock shifts, datum offsets, or sensor noise.
    * It is designed to be deterministic given the prepared input files and
      should not access raw repositories or external data sources directly.
    * The output is intended to be stitched with the post-NOAA corrected
      series using a separate transition step.

    See Also
    --------
    prepare_mrz_data
        Generates the canonical input series consumed by this function.
    martinez_stage
        Implements post-NOAA QA/QC, masking, and correction using NOAA data.
    transition_martinez_stage
        Blends the legacy and post-NOAA products into a continuous series.
    """

    mrz_cleaned = _read_cleaned(CLEANED_CSV).loc[start:end]
    mrz_ha = _read_value(str(paths.HARMONIC)).loc[start:end]
    sf = _read_value(str(paths.SF)).loc[start:end]
    mal = _read_value(str(paths.MAL)).loc[start:end]

    mrz_sub = cosine_lanczos(mrz_cleaned.interpolate(limit=4), "40h")
    sf_sub = cosine_lanczos(sf.interpolate(limit=5), "40h")
    mal_sub = cosine_lanczos(mal.interpolate(limit=4), "40h")

    filled_mrz_sub = fill_from_neighbor(target=mrz_sub, neighbor=mal_sub, method="substitute")["filled"]

    sfsub15 = sf_sub.resample("15min").interpolate(limit=4)
    blob = load_dfm_params(dfm_yaml)
    filled_mrz_sub = fill_from_neighbor(
        target=filled_mrz_sub,
        neighbor=sfsub15,
        method="dfm_trimbur_rw",
        params=blob,
    )["filled"]

    harm_res = mrz_ha - cosine_lanczos(mrz_ha, "40h")
    mrz_res = mrz_cleaned - filled_mrz_sub
    mrz_resful = fill_from_neighbor(target=mrz_res, neighbor=harm_res, method="resid_interp_linear")["filled"]

    final = (filled_mrz_sub + mrz_resful).rename("value")
    final.index.name = "datetime"
    paths.ensure_data()
    final.to_csv(paths.LEGACY_FILL, header=True, float_format="%.3f")

    fig, ax = plt.subplots(figsize=(10, 4))
    a, b = mrz_cleaned.align(final, join="inner")
    ax.plot(a.index, a.values, label="MRZ cleaned")
    ax.plot(b.index, b.values, label="MRZ legacy filled")
    ax.set_title("Martinez legacy fill (pre-NOAA)")
    ax.grid(True)
    ax.legend()
    plt.tight_layout()
    if show:
        plt.show()


if __name__ == "__main__":
    fill_mrz_legacy(start = pd.Timestamp("1990-01-01"),
                    end = NOAA_START,
                    dfm_yaml="dfm_trimbur_rw_mrz_sfsub.yaml")
